# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SpiderTool.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1462, 813)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_browser = QtWidgets.QWidget()
        self.tab_browser.setObjectName("tab_browser")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_browser)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_url = QtWidgets.QLineEdit(self.tab_browser)
        self.lineEdit_url.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.horizontalLayout.addWidget(self.lineEdit_url)
        self.pushButton_load = QtWidgets.QPushButton(self.tab_browser)
        self.pushButton_load.setObjectName("pushButton_load")
        self.horizontalLayout.addWidget(self.pushButton_load)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.tab_browser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.pushButton_browserSelect = QtWidgets.QPushButton(self.tab_browser)
        self.pushButton_browserSelect.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_browserSelect.setObjectName("pushButton_browserSelect")
        self.horizontalLayout.addWidget(self.pushButton_browserSelect)
        self.pushButton_browserUnselect = QtWidgets.QPushButton(self.tab_browser)
        self.pushButton_browserUnselect.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_browserUnselect.setObjectName("pushButton_browserUnselect")
        self.horizontalLayout.addWidget(self.pushButton_browserUnselect)
        self.pushButton_browserSelectParent = QtWidgets.QPushButton(self.tab_browser)
        self.pushButton_browserSelectParent.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_browserSelectParent.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_browserSelectParent.setObjectName("pushButton_browserSelectParent")
        self.horizontalLayout.addWidget(self.pushButton_browserSelectParent)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.widget_browser = QtWidgets.QWidget(self.tab_browser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_browser.sizePolicy().hasHeightForWidth())
        self.widget_browser.setSizePolicy(sizePolicy)
        self.widget_browser.setObjectName("widget_browser")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_browser)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_browser = QtWidgets.QVBoxLayout()
        self.verticalLayout_browser.setObjectName("verticalLayout_browser")
        self.verticalLayout_5.addLayout(self.verticalLayout_browser)
        self.verticalLayout_3.addWidget(self.widget_browser)
        self.tabWidget.addTab(self.tab_browser, "")
        self.tab_tasklist = QtWidgets.QWidget()
        self.tab_tasklist.setObjectName("tab_tasklist")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.tab_tasklist)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_tasklist)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_3 = QtWidgets.QWidget(self.tab_2)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_5.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_8 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setMinimumSize(QtCore.QSize(50, 0))
        self.widget_8.setMaximumSize(QtCore.QSize(50, 16777215))
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_7.setContentsMargins(0, 0, 5, 0)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_fieldAdd = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_fieldAdd.setObjectName("pushButton_fieldAdd")
        self.verticalLayout_7.addWidget(self.pushButton_fieldAdd)
        self.pushButton_fieldRemove = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_fieldRemove.setObjectName("pushButton_fieldRemove")
        self.verticalLayout_7.addWidget(self.pushButton_fieldRemove)
        self.pushButton_fieldCopy = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_fieldCopy.setObjectName("pushButton_fieldCopy")
        self.verticalLayout_7.addWidget(self.pushButton_fieldCopy)
        self.label_10 = QtWidgets.QLabel(self.widget_8)
        self.label_10.setMinimumSize(QtCore.QSize(0, 50))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.pushButton_fieldSave = QtWidgets.QPushButton(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_fieldSave.setFont(font)
        self.pushButton_fieldSave.setObjectName("pushButton_fieldSave")
        self.verticalLayout_7.addWidget(self.pushButton_fieldSave)
        self.label_4 = QtWidgets.QLabel(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 50))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.pushButton_fieldPreview = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_fieldPreview.setObjectName("pushButton_fieldPreview")
        self.verticalLayout_7.addWidget(self.pushButton_fieldPreview)
        self.pushButton_export = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_export.setObjectName("pushButton_export")
        self.verticalLayout_7.addWidget(self.pushButton_export)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.horizontalLayout_5.addWidget(self.widget_8)
        self.listView_fields = QtWidgets.QListView(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_fields.sizePolicy().hasHeightForWidth())
        self.listView_fields.setSizePolicy(sizePolicy)
        self.listView_fields.setMinimumSize(QtCore.QSize(150, 0))
        self.listView_fields.setMaximumSize(QtCore.QSize(150, 16777215))
        self.listView_fields.setObjectName("listView_fields")
        self.horizontalLayout_5.addWidget(self.listView_fields)
        self.widget_9 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_10 = QtWidgets.QWidget(self.widget_9)
        self.widget_10.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_22 = QtWidgets.QLabel(self.widget_10)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_7.addWidget(self.label_22)
        self.lineEdit_field_express = QtWidgets.QLineEdit(self.widget_10)
        self.lineEdit_field_express.setObjectName("lineEdit_field_express")
        self.horizontalLayout_7.addWidget(self.lineEdit_field_express)
        self.verticalLayout_9.addWidget(self.widget_10)
        self.widget_11 = QtWidgets.QWidget(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_11.sizePolicy().hasHeightForWidth())
        self.widget_11.setSizePolicy(sizePolicy)
        self.widget_11.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_11.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_11.setStyleSheet("")
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_9.addWidget(self.widget_11)
        self.groupBox = QtWidgets.QGroupBox(self.widget_9)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.plainTextEdit_code = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_code.setObjectName("plainTextEdit_code")
        self.horizontalLayout_22.addWidget(self.plainTextEdit_code)
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser.setLineWidth(1)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_22.addWidget(self.textBrowser)
        self.verticalLayout_9.addWidget(self.groupBox)
        self.widget_12 = QtWidgets.QWidget(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_12.sizePolicy().hasHeightForWidth())
        self.widget_12.setSizePolicy(sizePolicy)
        self.widget_12.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_12.setMaximumSize(QtCore.QSize(16777215, 150))
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_9.addWidget(self.widget_12)
        self.horizontalLayout_5.addWidget(self.widget_9)
        self.verticalLayout_6.addWidget(self.widget_3)
        self.widget_13 = QtWidgets.QWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_13.sizePolicy().hasHeightForWidth())
        self.widget_13.setSizePolicy(sizePolicy)
        self.widget_13.setMinimumSize(QtCore.QSize(0, 250))
        self.widget_13.setMaximumSize(QtCore.QSize(16777215, 250))
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_9.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_13)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.tableView_alldata = QtWidgets.QTableView(self.groupBox_2)
        self.tableView_alldata.setObjectName("tableView_alldata")
        self.horizontalLayout_24.addWidget(self.tableView_alldata)
        self.horizontalLayout_9.addWidget(self.groupBox_2)
        self.verticalLayout_6.addWidget(self.widget_13)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.horizontalLayout_13.addWidget(self.tabWidget_2)
        self.tabWidget.addTab(self.tab_tasklist, "")
        self.horizontalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.widget_right = QtWidgets.QWidget(self.widget)
        self.widget_right.setObjectName("widget_right")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_right)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_16 = QtWidgets.QWidget(self.widget_right)
        self.widget_16.setObjectName("widget_16")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_16)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget1 = QtWidgets.QWidget(self.widget_16)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_19 = QtWidgets.QWidget(self.widget1)
        self.widget_19.setStyleSheet("")
        self.widget_19.setObjectName("widget_19")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_19)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label = QtWidgets.QLabel(self.widget_19)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_14.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.verticalLayout_10.addWidget(self.widget_19)
        self.plainTextEdit_html = QtWidgets.QPlainTextEdit(self.widget1)
        self.plainTextEdit_html.setObjectName("plainTextEdit_html")
        self.verticalLayout_10.addWidget(self.plainTextEdit_html)
        self.horizontalLayout_2.addWidget(self.widget1)
        self.verticalLayout_8.addWidget(self.widget_16)
        self.widget_14 = QtWidgets.QWidget(self.widget_right)
        self.widget_14.setMinimumSize(QtCore.QSize(0, 20))
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_8.addWidget(self.widget_14)
        self.widget_17 = QtWidgets.QWidget(self.widget_right)
        self.widget_17.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_17.setObjectName("widget_17")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_17)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.widget_7 = QtWidgets.QWidget(self.widget_17)
        self.widget_7.setStyleSheet("")
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_5 = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_17.addWidget(self.label_5)
        self.pushButton_extract_link = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_extract_link.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton_extract_link.setObjectName("pushButton_extract_link")
        self.horizontalLayout_17.addWidget(self.pushButton_extract_link)
        self.pushButton_extract_text = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_extract_text.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton_extract_text.setObjectName("pushButton_extract_text")
        self.horizontalLayout_17.addWidget(self.pushButton_extract_text)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem3)
        self.pushButton_express_save_field = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_express_save_field.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton_express_save_field.setObjectName("pushButton_express_save_field")
        self.horizontalLayout_17.addWidget(self.pushButton_express_save_field)
        self.verticalLayout_13.addWidget(self.widget_7)
        self.widget_18 = QtWidgets.QWidget(self.widget_17)
        self.widget_18.setMinimumSize(QtCore.QSize(0, 20))
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_18)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_13.addWidget(self.widget_18)
        self.widget_20 = QtWidgets.QWidget(self.widget_17)
        self.widget_20.setStyleSheet("")
        self.widget_20.setObjectName("widget_20")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.widget_20)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_12 = QtWidgets.QLabel(self.widget_20)
        font = QtGui.QFont()
        font.setFamily("Adobe 楷体 Std R")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_18.addWidget(self.label_12)
        self.lineEdit_express = QtWidgets.QLineEdit(self.widget_20)
        self.lineEdit_express.setObjectName("lineEdit_express")
        self.horizontalLayout_18.addWidget(self.lineEdit_express)
        self.pushButton_extract_preview = QtWidgets.QPushButton(self.widget_20)
        self.pushButton_extract_preview.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton_extract_preview.setObjectName("pushButton_extract_preview")
        self.horizontalLayout_18.addWidget(self.pushButton_extract_preview)
        self.verticalLayout_13.addWidget(self.widget_20)
        self.plainTextEdit_field_value = QtWidgets.QPlainTextEdit(self.widget_17)
        self.plainTextEdit_field_value.setObjectName("plainTextEdit_field_value")
        self.verticalLayout_13.addWidget(self.plainTextEdit_field_value)
        self.verticalLayout_8.addWidget(self.widget_17)
        self.verticalLayout_8.setStretch(0, 5)
        self.verticalLayout_8.setStretch(2, 5)
        self.horizontalLayout_6.addWidget(self.widget_right)
        self.horizontalLayout_6.setStretch(0, 7)
        self.horizontalLayout_6.setStretch(1, 3)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1462, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_load.setText(_translate("MainWindow", "加载页面"))
        self.pushButton_browserSelect.setText(_translate("MainWindow", "开始选择"))
        self.pushButton_browserUnselect.setText(_translate("MainWindow", "取消选择"))
        self.pushButton_browserSelectParent.setText(_translate("MainWindow", "选择上一级"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_browser), _translate("MainWindow", "浏览器"))
        self.pushButton_fieldAdd.setText(_translate("MainWindow", "添加"))
        self.pushButton_fieldRemove.setText(_translate("MainWindow", "删除"))
        self.pushButton_fieldCopy.setText(_translate("MainWindow", "复制"))
        self.pushButton_fieldSave.setText(_translate("MainWindow", "保存"))
        self.pushButton_fieldPreview.setText(_translate("MainWindow", "预览"))
        self.pushButton_export.setText(_translate("MainWindow", "导出"))
        self.label_22.setText(_translate("MainWindow", "xpath表达式："))
        self.groupBox.setTitle(_translate("MainWindow", "处理数据"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">定义一个javascript函数，函数名只能是parse，参数就是需要处理的字段值，结构如下</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">function parse(s){</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  //这里写自己的代码</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  return s;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">}</p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "数据展示"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "提取字段"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tasklist), _translate("MainWindow", "设计器"))
        self.label.setText(_translate("MainWindow", "页面结构>>"))
        self.label_5.setText(_translate("MainWindow", "提取操作>>"))
        self.pushButton_extract_link.setText(_translate("MainWindow", "超链接"))
        self.pushButton_extract_text.setText(_translate("MainWindow", "文本"))
        self.pushButton_express_save_field.setText(_translate("MainWindow", "保存字段"))
        self.label_12.setText(_translate("MainWindow", "表达式"))
        self.pushButton_extract_preview.setText(_translate("MainWindow", "浏览数据"))
