# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ToolWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1023, 771)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_url = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.horizontalLayout.addWidget(self.lineEdit_url)
        self.pushButton_load = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_load.setObjectName("pushButton_load")
        self.horizontalLayout.addWidget(self.pushButton_load)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_browserSelect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_browserSelect.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_browserSelect.setObjectName("pushButton_browserSelect")
        self.horizontalLayout.addWidget(self.pushButton_browserSelect)
        self.pushButton_browserUnselect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_browserUnselect.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_browserUnselect.setObjectName("pushButton_browserUnselect")
        self.horizontalLayout.addWidget(self.pushButton_browserUnselect)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.browserLayout = QtWidgets.QHBoxLayout()
        self.browserLayout.setSpacing(5)
        self.browserLayout.setObjectName("browserLayout")
        self.verticalLayout_tools = QtWidgets.QVBoxLayout()
        self.verticalLayout_tools.setObjectName("verticalLayout_tools")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_tools.addItem(spacerItem1)
        self.browserLayout.addLayout(self.verticalLayout_tools)
        self.verticalLayout_2.addLayout(self.browserLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_7 = QtWidgets.QWidget(self.widget)
        self.widget_7.setMinimumSize(QtCore.QSize(100, 0))
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(20)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_11.addWidget(self.label)
        self.pushButton_browserExtractText = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_browserExtractText.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_browserExtractText.setObjectName("pushButton_browserExtractText")
        self.horizontalLayout_11.addWidget(self.pushButton_browserExtractText)
        self.pushButton_browserSelectParent = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_browserSelectParent.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_browserSelectParent.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_browserSelectParent.setObjectName("pushButton_browserSelectParent")
        self.horizontalLayout_11.addWidget(self.pushButton_browserSelectParent)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        self.plainTextEdit_html = QtWidgets.QPlainTextEdit(self.widget_7)
        self.plainTextEdit_html.setObjectName("plainTextEdit_html")
        self.verticalLayout_11.addWidget(self.plainTextEdit_html)
        self.horizontalLayout_2.addWidget(self.widget_7)
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setMinimumSize(QtCore.QSize(100, 0))
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(20)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.pushButton_defineField_addRow = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_defineField_addRow.setObjectName("pushButton_defineField_addRow")
        self.horizontalLayout_8.addWidget(self.pushButton_defineField_addRow)
        self.pushButton_defineField_removeRow = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_defineField_removeRow.setObjectName("pushButton_defineField_removeRow")
        self.horizontalLayout_8.addWidget(self.pushButton_defineField_removeRow)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.tableWidget_defineField = QtWidgets.QTableWidget(self.widget_5)
        self.tableWidget_defineField.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget_defineField.setObjectName("tableWidget_defineField")
        self.tableWidget_defineField.setColumnCount(0)
        self.tableWidget_defineField.setRowCount(0)
        self.verticalLayout_8.addWidget(self.tableWidget_defineField)
        self.horizontalLayout_2.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.widget)
        self.widget_6.setMinimumSize(QtCore.QSize(100, 0))
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(20)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        self.pushButton_alldata_showData = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_alldata_showData.setObjectName("pushButton_alldata_showData")
        self.horizontalLayout_10.addWidget(self.pushButton_alldata_showData)
        self.pushButton_alldata_export = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_alldata_export.setObjectName("pushButton_alldata_export")
        self.horizontalLayout_10.addWidget(self.pushButton_alldata_export)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        self.tableView_alldata = QtWidgets.QTableView(self.widget_6)
        self.tableView_alldata.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableView_alldata.setObjectName("tableView_alldata")
        self.verticalLayout_10.addWidget(self.tableView_alldata)
        self.horizontalLayout_2.addWidget(self.widget_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(0, 5)
        self.verticalLayout_2.setStretch(1, 5)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1023, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_load.clicked.connect(MainWindow.loadUrl)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_load.setText(_translate("MainWindow", "加载页面"))
        self.pushButton_browserSelect.setText(_translate("MainWindow", "开始选择"))
        self.pushButton_browserUnselect.setText(_translate("MainWindow", "取消选择"))
        self.label.setText(_translate("MainWindow", "页面结构>>"))
        self.pushButton_browserExtractText.setText(_translate("MainWindow", "提取文本"))
        self.pushButton_browserSelectParent.setText(_translate("MainWindow", "选择上一级"))
        self.label_2.setText(_translate("MainWindow", "字段管理>>"))
        self.pushButton_defineField_addRow.setText(_translate("MainWindow", "添加行"))
        self.pushButton_defineField_removeRow.setText(_translate("MainWindow", "删除行"))
        self.label_4.setText(_translate("MainWindow", "数据管理>>"))
        self.pushButton_alldata_showData.setText(_translate("MainWindow", "预览数据"))
        self.pushButton_alldata_export.setText(_translate("MainWindow", "导出数据"))
