# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ToolWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1482, 808)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_browser = QtWidgets.QWidget()
        self.tab_browser.setObjectName("tab_browser")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_browser)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_url = QtWidgets.QLineEdit(self.tab_browser)
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.horizontalLayout.addWidget(self.lineEdit_url)
        self.pushButton_load = QtWidgets.QPushButton(self.tab_browser)
        self.pushButton_load.setObjectName("pushButton_load")
        self.horizontalLayout.addWidget(self.pushButton_load)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_browserSelect = QtWidgets.QPushButton(self.tab_browser)
        self.pushButton_browserSelect.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_browserSelect.setObjectName("pushButton_browserSelect")
        self.horizontalLayout.addWidget(self.pushButton_browserSelect)
        self.pushButton_browserUnselect = QtWidgets.QPushButton(self.tab_browser)
        self.pushButton_browserUnselect.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_browserUnselect.setObjectName("pushButton_browserUnselect")
        self.horizontalLayout.addWidget(self.pushButton_browserUnselect)
        self.label_2 = QtWidgets.QLabel(self.tab_browser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.pushButton_browserExtractText = QtWidgets.QPushButton(self.tab_browser)
        self.pushButton_browserExtractText.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_browserExtractText.setObjectName("pushButton_browserExtractText")
        self.horizontalLayout.addWidget(self.pushButton_browserExtractText)
        self.pushButton_browserSelectParent = QtWidgets.QPushButton(self.tab_browser)
        self.pushButton_browserSelectParent.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_browserSelectParent.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_browserSelectParent.setObjectName("pushButton_browserSelectParent")
        self.horizontalLayout.addWidget(self.pushButton_browserSelectParent)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.widget_browser = QtWidgets.QWidget(self.tab_browser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_browser.sizePolicy().hasHeightForWidth())
        self.widget_browser.setSizePolicy(sizePolicy)
        self.widget_browser.setObjectName("widget_browser")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_browser)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_browser = QtWidgets.QVBoxLayout()
        self.verticalLayout_browser.setObjectName("verticalLayout_browser")
        self.verticalLayout_5.addLayout(self.verticalLayout_browser)
        self.verticalLayout_3.addWidget(self.widget_browser)
        self.tabWidget.addTab(self.tab_browser, "")
        self.tab_tasklist = QtWidgets.QWidget()
        self.tab_tasklist.setObjectName("tab_tasklist")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.tab_tasklist)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_tasklist)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_1)
        self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_2 = QtWidgets.QWidget(self.tab_1)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4.addWidget(self.widget_2)
        self.plainTextEdit_urls = QtWidgets.QPlainTextEdit(self.tab_1)
        self.plainTextEdit_urls.setObjectName("plainTextEdit_urls")
        self.verticalLayout_4.addWidget(self.plainTextEdit_urls)
        self.tabWidget_2.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_3 = QtWidgets.QWidget(self.tab_2)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_5.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_8 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setMinimumSize(QtCore.QSize(50, 0))
        self.widget_8.setMaximumSize(QtCore.QSize(50, 16777215))
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_fieldAdd = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_fieldAdd.setObjectName("pushButton_fieldAdd")
        self.verticalLayout_7.addWidget(self.pushButton_fieldAdd)
        self.pushButton_fieldRemove = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_fieldRemove.setObjectName("pushButton_fieldRemove")
        self.verticalLayout_7.addWidget(self.pushButton_fieldRemove)
        self.pushButton_fieldCopy = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_fieldCopy.setObjectName("pushButton_fieldCopy")
        self.verticalLayout_7.addWidget(self.pushButton_fieldCopy)
        self.label_10 = QtWidgets.QLabel(self.widget_8)
        self.label_10.setMinimumSize(QtCore.QSize(0, 50))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.pushButton_fieldSave = QtWidgets.QPushButton(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_fieldSave.setFont(font)
        self.pushButton_fieldSave.setObjectName("pushButton_fieldSave")
        self.verticalLayout_7.addWidget(self.pushButton_fieldSave)
        self.label_4 = QtWidgets.QLabel(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 50))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.pushButton_fieldPreview = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_fieldPreview.setObjectName("pushButton_fieldPreview")
        self.verticalLayout_7.addWidget(self.pushButton_fieldPreview)
        self.pushButton_export = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_export.setObjectName("pushButton_export")
        self.verticalLayout_7.addWidget(self.pushButton_export)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.horizontalLayout_5.addWidget(self.widget_8)
        self.listView_fields = QtWidgets.QListView(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_fields.sizePolicy().hasHeightForWidth())
        self.listView_fields.setSizePolicy(sizePolicy)
        self.listView_fields.setMinimumSize(QtCore.QSize(150, 0))
        self.listView_fields.setMaximumSize(QtCore.QSize(150, 16777215))
        self.listView_fields.setObjectName("listView_fields")
        self.horizontalLayout_5.addWidget(self.listView_fields)
        self.widget_9 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_10 = QtWidgets.QWidget(self.widget_9)
        self.widget_10.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.radioButton_field_xpath = QtWidgets.QRadioButton(self.widget_10)
        self.radioButton_field_xpath.setChecked(True)
        self.radioButton_field_xpath.setObjectName("radioButton_field_xpath")
        self.horizontalLayout_7.addWidget(self.radioButton_field_xpath)
        self.lineEdit_field_express = QtWidgets.QLineEdit(self.widget_10)
        self.lineEdit_field_express.setObjectName("lineEdit_field_express")
        self.horizontalLayout_7.addWidget(self.lineEdit_field_express)
        self.verticalLayout_9.addWidget(self.widget_10)
        self.widget_11 = QtWidgets.QWidget(self.widget_9)
        self.widget_11.setStyleSheet("")
        self.widget_11.setObjectName("widget_11")
        self.radioButton_field_headtail = QtWidgets.QRadioButton(self.widget_11)
        self.radioButton_field_headtail.setGeometry(QtCore.QRect(10, 70, 61, 19))
        self.radioButton_field_headtail.setObjectName("radioButton_field_headtail")
        self.checkBox_field_headinclude = QtWidgets.QCheckBox(self.widget_11)
        self.checkBox_field_headinclude.setGeometry(QtCore.QRect(100, 70, 91, 19))
        self.checkBox_field_headinclude.setChecked(True)
        self.checkBox_field_headinclude.setObjectName("checkBox_field_headinclude")
        self.checkBox_field_tailinclude = QtWidgets.QCheckBox(self.widget_11)
        self.checkBox_field_tailinclude.setGeometry(QtCore.QRect(440, 70, 91, 19))
        self.checkBox_field_tailinclude.setObjectName("checkBox_field_tailinclude")
        self.textEdit_field_head = QtWidgets.QTextEdit(self.widget_11)
        self.textEdit_field_head.setGeometry(QtCore.QRect(190, 0, 220, 160))
        self.textEdit_field_head.setObjectName("textEdit_field_head")
        self.textEdit_field_tail = QtWidgets.QTextEdit(self.widget_11)
        self.textEdit_field_tail.setGeometry(QtCore.QRect(530, 0, 220, 160))
        self.textEdit_field_tail.setObjectName("textEdit_field_tail")
        self.verticalLayout_9.addWidget(self.widget_11)
        self.widget_12 = QtWidgets.QWidget(self.widget_9)
        self.widget_12.setObjectName("widget_12")
        self.label_6 = QtWidgets.QLabel(self.widget_12)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 72, 15))
        self.label_6.setObjectName("label_6")
        self.lineEdit_field_datepattern = QtWidgets.QLineEdit(self.widget_12)
        self.lineEdit_field_datepattern.setGeometry(QtCore.QRect(90, 10, 321, 21))
        self.lineEdit_field_datepattern.setObjectName("lineEdit_field_datepattern")
        self.verticalLayout_9.addWidget(self.widget_12)
        self.widget_4 = QtWidgets.QWidget(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.widget_4)
        self.label_7.setMinimumSize(QtCore.QSize(50, 0))
        self.label_7.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.checkBox_pager_is = QtWidgets.QCheckBox(self.widget_4)
        self.checkBox_pager_is.setObjectName("checkBox_pager_is")
        self.horizontalLayout_6.addWidget(self.checkBox_pager_is)
        self.lineEdit_pager_express = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_pager_express.setObjectName("lineEdit_pager_express")
        self.horizontalLayout_6.addWidget(self.lineEdit_pager_express)
        self.pushButton_pager_preview = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_pager_preview.setObjectName("pushButton_pager_preview")
        self.horizontalLayout_6.addWidget(self.pushButton_pager_preview)
        self.verticalLayout_9.addWidget(self.widget_4)
        self.horizontalLayout_5.addWidget(self.widget_9)
        self.verticalLayout_6.addWidget(self.widget_3)
        self.widget_13 = QtWidgets.QWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_13.sizePolicy().hasHeightForWidth())
        self.widget_13.setSizePolicy(sizePolicy)
        self.widget_13.setMinimumSize(QtCore.QSize(0, 250))
        self.widget_13.setMaximumSize(QtCore.QSize(16777215, 250))
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_9.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tableView_alldata = QtWidgets.QTableView(self.widget_13)
        self.tableView_alldata.setObjectName("tableView_alldata")
        self.horizontalLayout_9.addWidget(self.tableView_alldata)
        self.verticalLayout_6.addWidget(self.widget_13)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_14 = QtWidgets.QWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_14.sizePolicy().hasHeightForWidth())
        self.widget_14.setSizePolicy(sizePolicy)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_12.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.checkBox_savefile_is = QtWidgets.QCheckBox(self.widget_14)
        self.checkBox_savefile_is.setObjectName("checkBox_savefile_is")
        self.horizontalLayout_12.addWidget(self.checkBox_savefile_is)
        self.lineEdit_savefile_filename = QtWidgets.QLineEdit(self.widget_14)
        self.lineEdit_savefile_filename.setObjectName("lineEdit_savefile_filename")
        self.horizontalLayout_12.addWidget(self.lineEdit_savefile_filename)
        self.label_8 = QtWidgets.QLabel(self.widget_14)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_12.addWidget(self.label_8)
        self.lineEdit_savefile_sep = QtWidgets.QLineEdit(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_savefile_sep.sizePolicy().hasHeightForWidth())
        self.lineEdit_savefile_sep.setSizePolicy(sizePolicy)
        self.lineEdit_savefile_sep.setObjectName("lineEdit_savefile_sep")
        self.horizontalLayout_12.addWidget(self.lineEdit_savefile_sep)
        self.verticalLayout_12.addWidget(self.widget_14)
        self.frame = QtWidgets.QFrame(self.tab_3)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_12.addWidget(self.frame)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_5 = QtWidgets.QWidget(self.tab_4)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_ = QtWidgets.QLabel(self.widget_5)
        self.label_.setObjectName("label_")
        self.horizontalLayout_8.addWidget(self.label_)
        self.lineEdit_taskName = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_taskName.setText("")
        self.lineEdit_taskName.setObjectName("lineEdit_taskName")
        self.horizontalLayout_8.addWidget(self.lineEdit_taskName)
        self.label_9 = QtWidgets.QLabel(self.widget_5)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.lineEdit_schedulePeriod = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_schedulePeriod.setText("")
        self.lineEdit_schedulePeriod.setObjectName("lineEdit_schedulePeriod")
        self.horizontalLayout_8.addWidget(self.lineEdit_schedulePeriod)
        self.checkBox_duplicate = QtWidgets.QCheckBox(self.widget_5)
        self.checkBox_duplicate.setObjectName("checkBox_duplicate")
        self.horizontalLayout_8.addWidget(self.checkBox_duplicate)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.widget_15 = QtWidgets.QWidget(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_15.sizePolicy().hasHeightForWidth())
        self.widget_15.setSizePolicy(sizePolicy)
        self.widget_15.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.widget_15.setObjectName("widget_15")
        self.label_3 = QtWidgets.QLabel(self.widget_15)
        self.label_3.setGeometry(QtCore.QRect(70, 30, 72, 15))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.widget_15)
        self.widget_6 = QtWidgets.QWidget(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 80))
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 80))
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.pushButton_exportTask = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_exportTask.setMinimumSize(QtCore.QSize(0, 70))
        self.pushButton_exportTask.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_exportTask.setFont(font)
        self.pushButton_exportTask.setObjectName("pushButton_exportTask")
        self.horizontalLayout_10.addWidget(self.pushButton_exportTask)
        self.verticalLayout_2.addWidget(self.widget_6)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.horizontalLayout_13.addWidget(self.tabWidget_2)
        self.tabWidget.addTab(self.tab_tasklist, "")
        self.horizontalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_7 = QtWidgets.QWidget(self.widget)
        self.widget_7.setMinimumSize(QtCore.QSize(100, 0))
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(20)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_11.addWidget(self.label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        self.plainTextEdit_html = QtWidgets.QPlainTextEdit(self.widget_7)
        self.plainTextEdit_html.setObjectName("plainTextEdit_html")
        self.verticalLayout_11.addWidget(self.plainTextEdit_html)
        self.horizontalLayout_2.addWidget(self.widget_7)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_14.setStretch(0, 7)
        self.horizontalLayout_14.setStretch(1, 3)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1482, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.pushButton_load.clicked.connect(MainWindow.loadUrl)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_load.setText(_translate("MainWindow", "加载页面"))
        self.pushButton_browserSelect.setText(_translate("MainWindow", "开始选择"))
        self.pushButton_browserUnselect.setText(_translate("MainWindow", "取消选择"))
        self.pushButton_browserExtractText.setText(_translate("MainWindow", "提取文本"))
        self.pushButton_browserSelectParent.setText(_translate("MainWindow", "选择上一级"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_browser), _translate("MainWindow", "浏览器"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_1), _translate("MainWindow", "1、起始网址"))
        self.pushButton_fieldAdd.setText(_translate("MainWindow", "添加"))
        self.pushButton_fieldRemove.setText(_translate("MainWindow", "删除"))
        self.pushButton_fieldCopy.setText(_translate("MainWindow", "复制"))
        self.pushButton_fieldSave.setText(_translate("MainWindow", "保存"))
        self.pushButton_fieldPreview.setText(_translate("MainWindow", "预览"))
        self.pushButton_export.setText(_translate("MainWindow", "导出"))
        self.radioButton_field_xpath.setText(_translate("MainWindow", "xpath"))
        self.radioButton_field_headtail.setText(_translate("MainWindow", "头尾"))
        self.checkBox_field_headinclude.setText(_translate("MainWindow", "包含头部"))
        self.checkBox_field_tailinclude.setText(_translate("MainWindow", "包含尾部"))
        self.label_6.setText(_translate("MainWindow", "日期格式："))
        self.checkBox_pager_is.setText(_translate("MainWindow", "分页"))
        self.pushButton_pager_preview.setText(_translate("MainWindow", "预览"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "2、提取字段"))
        self.checkBox_savefile_is.setText(_translate("MainWindow", "保存到文件"))
        self.label_8.setText(_translate("MainWindow", "分隔符"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "3、发布信息"))
        self.label_.setText(_translate("MainWindow", "任务名称"))
        self.label_9.setText(_translate("MainWindow", "       调度周期"))
        self.checkBox_duplicate.setText(_translate("MainWindow", " 抓取时去重"))
        self.label_3.setText(_translate("MainWindow", "待添加"))
        self.pushButton_exportTask.setText(_translate("MainWindow", "导出任务"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "4、爬虫设置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tasklist), _translate("MainWindow", "设计器"))
        self.label.setText(_translate("MainWindow", "页面结构>>"))
