# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ToolWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1462, 813)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_autopagermode = QtWidgets.QWidget(self.widget)
        self.widget_autopagermode.setMinimumSize(QtCore.QSize(100, 0))
        self.widget_autopagermode.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_autopagermode.setStyleSheet("")
        self.widget_autopagermode.setObjectName("widget_autopagermode")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_autopagermode)
        self.verticalLayout_11.setContentsMargins(5, 1, 5, 1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_4 = QtWidgets.QWidget(self.widget_autopagermode)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_7 = QtWidgets.QLabel(self.widget_4)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_14.addWidget(self.label_7)
        self.lineEdit_pager_xpath = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_pager_xpath.setObjectName("lineEdit_pager_xpath")
        self.verticalLayout_14.addWidget(self.lineEdit_pager_xpath)
        self.verticalLayout_11.addWidget(self.widget_4)
        self.widget_2 = QtWidgets.QWidget(self.widget_autopagermode)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setContentsMargins(0, 10, 0, 10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_18 = QtWidgets.QLabel(self.widget_2)
        self.label_18.setMinimumSize(QtCore.QSize(55, 0))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_4.addWidget(self.label_18)
        self.lineEdit_pager_times = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_pager_times.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_pager_times.setObjectName("lineEdit_pager_times")
        self.horizontalLayout_4.addWidget(self.lineEdit_pager_times)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_11.addWidget(self.widget_2)
        self.widget_21 = QtWidgets.QWidget(self.widget_autopagermode)
        self.widget_21.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.widget_21)
        self.horizontalLayout_20.setContentsMargins(0, 10, 0, 10)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_20 = QtWidgets.QLabel(self.widget_21)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_20.addWidget(self.label_20)
        self.lineEdit_pager_halt = QtWidgets.QLineEdit(self.widget_21)
        self.lineEdit_pager_halt.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_pager_halt.setObjectName("lineEdit_pager_halt")
        self.horizontalLayout_20.addWidget(self.lineEdit_pager_halt)
        self.label_21 = QtWidgets.QLabel(self.widget_21)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_20.addWidget(self.label_21)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem1)
        self.verticalLayout_11.addWidget(self.widget_21)
        self.pushButton_pager_test = QtWidgets.QPushButton(self.widget_autopagermode)
        self.pushButton_pager_test.setObjectName("pushButton_pager_test")
        self.verticalLayout_11.addWidget(self.pushButton_pager_test)
        self.widget_22 = QtWidgets.QWidget(self.widget_autopagermode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_22.sizePolicy().hasHeightForWidth())
        self.widget_22.setSizePolicy(sizePolicy)
        self.widget_22.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_22.setObjectName("widget_22")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_22)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_11.addWidget(self.widget_22)
        self.widget_24 = QtWidgets.QWidget(self.widget_autopagermode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_24.sizePolicy().hasHeightForWidth())
        self.widget_24.setSizePolicy(sizePolicy)
        self.widget_24.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_24.setObjectName("widget_24")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.widget_24)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_11.addWidget(self.widget_24)
        self.widget_26 = QtWidgets.QWidget(self.widget_autopagermode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_26.sizePolicy().hasHeightForWidth())
        self.widget_26.setSizePolicy(sizePolicy)
        self.widget_26.setObjectName("widget_26")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.widget_26)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_17 = QtWidgets.QLabel(self.widget_26)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_18.addWidget(self.label_17)
        self.verticalLayout_11.addWidget(self.widget_26)
        self.horizontalLayout_6.addWidget(self.widget_autopagermode)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_browser = QtWidgets.QWidget()
        self.tab_browser.setObjectName("tab_browser")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_browser)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_autopager = QtWidgets.QCheckBox(self.tab_browser)
        self.checkBox_autopager.setObjectName("checkBox_autopager")
        self.horizontalLayout.addWidget(self.checkBox_autopager)
        self.lineEdit_url = QtWidgets.QLineEdit(self.tab_browser)
        self.lineEdit_url.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.horizontalLayout.addWidget(self.lineEdit_url)
        self.pushButton_load = QtWidgets.QPushButton(self.tab_browser)
        self.pushButton_load.setObjectName("pushButton_load")
        self.horizontalLayout.addWidget(self.pushButton_load)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_browserSelect = QtWidgets.QPushButton(self.tab_browser)
        self.pushButton_browserSelect.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_browserSelect.setObjectName("pushButton_browserSelect")
        self.horizontalLayout.addWidget(self.pushButton_browserSelect)
        self.pushButton_browserUnselect = QtWidgets.QPushButton(self.tab_browser)
        self.pushButton_browserUnselect.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_browserUnselect.setObjectName("pushButton_browserUnselect")
        self.horizontalLayout.addWidget(self.pushButton_browserUnselect)
        self.label_2 = QtWidgets.QLabel(self.tab_browser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.widget_browser = QtWidgets.QWidget(self.tab_browser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_browser.sizePolicy().hasHeightForWidth())
        self.widget_browser.setSizePolicy(sizePolicy)
        self.widget_browser.setObjectName("widget_browser")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_browser)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_browser = QtWidgets.QVBoxLayout()
        self.verticalLayout_browser.setObjectName("verticalLayout_browser")
        self.verticalLayout_5.addLayout(self.verticalLayout_browser)
        self.verticalLayout_3.addWidget(self.widget_browser)
        self.tabWidget.addTab(self.tab_browser, "")
        self.tab_tasklist = QtWidgets.QWidget()
        self.tab_tasklist.setObjectName("tab_tasklist")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.tab_tasklist)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_tasklist)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.tab_1)
        self.horizontalLayout_19.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.plainTextEdit_urls = QtWidgets.QPlainTextEdit(self.tab_1)
        self.plainTextEdit_urls.setObjectName("plainTextEdit_urls")
        self.horizontalLayout_19.addWidget(self.plainTextEdit_urls)
        self.tabWidget_2.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_3 = QtWidgets.QWidget(self.tab_2)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_5.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_8 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setMinimumSize(QtCore.QSize(50, 0))
        self.widget_8.setMaximumSize(QtCore.QSize(50, 16777215))
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_7.setContentsMargins(0, 0, 5, 0)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_fieldAdd = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_fieldAdd.setObjectName("pushButton_fieldAdd")
        self.verticalLayout_7.addWidget(self.pushButton_fieldAdd)
        self.pushButton_fieldRemove = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_fieldRemove.setObjectName("pushButton_fieldRemove")
        self.verticalLayout_7.addWidget(self.pushButton_fieldRemove)
        self.pushButton_fieldCopy = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_fieldCopy.setObjectName("pushButton_fieldCopy")
        self.verticalLayout_7.addWidget(self.pushButton_fieldCopy)
        self.label_10 = QtWidgets.QLabel(self.widget_8)
        self.label_10.setMinimumSize(QtCore.QSize(0, 50))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.pushButton_fieldSave = QtWidgets.QPushButton(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_fieldSave.setFont(font)
        self.pushButton_fieldSave.setObjectName("pushButton_fieldSave")
        self.verticalLayout_7.addWidget(self.pushButton_fieldSave)
        self.label_4 = QtWidgets.QLabel(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 50))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.pushButton_fieldPreview = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_fieldPreview.setObjectName("pushButton_fieldPreview")
        self.verticalLayout_7.addWidget(self.pushButton_fieldPreview)
        self.pushButton_export = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_export.setObjectName("pushButton_export")
        self.verticalLayout_7.addWidget(self.pushButton_export)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.horizontalLayout_5.addWidget(self.widget_8)
        self.listView_fields = QtWidgets.QListView(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_fields.sizePolicy().hasHeightForWidth())
        self.listView_fields.setSizePolicy(sizePolicy)
        self.listView_fields.setMinimumSize(QtCore.QSize(150, 0))
        self.listView_fields.setMaximumSize(QtCore.QSize(150, 16777215))
        self.listView_fields.setObjectName("listView_fields")
        self.horizontalLayout_5.addWidget(self.listView_fields)
        self.widget_9 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_10 = QtWidgets.QWidget(self.widget_9)
        self.widget_10.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_22 = QtWidgets.QLabel(self.widget_10)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_7.addWidget(self.label_22)
        self.lineEdit_field_express = QtWidgets.QLineEdit(self.widget_10)
        self.lineEdit_field_express.setObjectName("lineEdit_field_express")
        self.horizontalLayout_7.addWidget(self.lineEdit_field_express)
        self.verticalLayout_9.addWidget(self.widget_10)
        self.groupBox = QtWidgets.QGroupBox(self.widget_9)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.plainTextEdit_code = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_code.setObjectName("plainTextEdit_code")
        self.horizontalLayout_22.addWidget(self.plainTextEdit_code)
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser.setLineWidth(1)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_22.addWidget(self.textBrowser)
        self.verticalLayout_9.addWidget(self.groupBox)
        self.widget_11 = QtWidgets.QWidget(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_11.sizePolicy().hasHeightForWidth())
        self.widget_11.setSizePolicy(sizePolicy)
        self.widget_11.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_11.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_11.setStyleSheet("")
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_9.addWidget(self.widget_11)
        self.widget_12 = QtWidgets.QWidget(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_12.sizePolicy().hasHeightForWidth())
        self.widget_12.setSizePolicy(sizePolicy)
        self.widget_12.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_12.setMaximumSize(QtCore.QSize(16777215, 150))
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_9.addWidget(self.widget_12)
        self.horizontalLayout_5.addWidget(self.widget_9)
        self.verticalLayout_6.addWidget(self.widget_3)
        self.widget_13 = QtWidgets.QWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_13.sizePolicy().hasHeightForWidth())
        self.widget_13.setSizePolicy(sizePolicy)
        self.widget_13.setMinimumSize(QtCore.QSize(0, 250))
        self.widget_13.setMaximumSize(QtCore.QSize(16777215, 250))
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_9.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_13)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.tableView_alldata = QtWidgets.QTableView(self.groupBox_2)
        self.tableView_alldata.setObjectName("tableView_alldata")
        self.horizontalLayout_24.addWidget(self.tableView_alldata)
        self.horizontalLayout_9.addWidget(self.groupBox_2)
        self.verticalLayout_6.addWidget(self.widget_13)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_23 = QtWidgets.QWidget(self.tab_3)
        self.widget_23.setObjectName("widget_23")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.widget_23)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.checkBox_savefile_is = QtWidgets.QCheckBox(self.widget_23)
        self.checkBox_savefile_is.setObjectName("checkBox_savefile_is")
        self.horizontalLayout_21.addWidget(self.checkBox_savefile_is)
        self.checkBox_savemysql_is = QtWidgets.QCheckBox(self.widget_23)
        self.checkBox_savemysql_is.setObjectName("checkBox_savemysql_is")
        self.horizontalLayout_21.addWidget(self.checkBox_savemysql_is)
        self.verticalLayout_12.addWidget(self.widget_23)
        self.groupBox_saveFile = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_saveFile.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_saveFile.setObjectName("groupBox_saveFile")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.groupBox_saveFile)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.pushButton_saveFile_chooseName = QtWidgets.QPushButton(self.groupBox_saveFile)
        self.pushButton_saveFile_chooseName.setObjectName("pushButton_saveFile_chooseName")
        self.horizontalLayout_23.addWidget(self.pushButton_saveFile_chooseName)
        self.lineEdit_savefile_filename = QtWidgets.QLineEdit(self.groupBox_saveFile)
        self.lineEdit_savefile_filename.setObjectName("lineEdit_savefile_filename")
        self.horizontalLayout_23.addWidget(self.lineEdit_savefile_filename)
        self.label_8 = QtWidgets.QLabel(self.groupBox_saveFile)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_23.addWidget(self.label_8)
        self.lineEdit_savefile_sep = QtWidgets.QLineEdit(self.groupBox_saveFile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_savefile_sep.sizePolicy().hasHeightForWidth())
        self.lineEdit_savefile_sep.setSizePolicy(sizePolicy)
        self.lineEdit_savefile_sep.setObjectName("lineEdit_savefile_sep")
        self.horizontalLayout_23.addWidget(self.lineEdit_savefile_sep)
        self.verticalLayout_12.addWidget(self.groupBox_saveFile)
        self.groupBox_savemysql = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_savemysql.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_savemysql.setObjectName("groupBox_savemysql")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox_savemysql)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_13 = QtWidgets.QLabel(self.groupBox_savemysql)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_savemysql)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_14 = QtWidgets.QLabel(self.groupBox_savemysql)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_savemysql)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_15 = QtWidgets.QLabel(self.groupBox_savemysql)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_savemysql)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.horizontalLayout_12.addLayout(self.formLayout)
        self.verticalLayout_12.addWidget(self.groupBox_savemysql)
        self.frame = QtWidgets.QFrame(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_12.addWidget(self.frame)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_5 = QtWidgets.QWidget(self.tab_4)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_ = QtWidgets.QLabel(self.widget_5)
        self.label_.setObjectName("label_")
        self.horizontalLayout_8.addWidget(self.label_)
        self.lineEdit_taskName = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_taskName.setText("")
        self.lineEdit_taskName.setObjectName("lineEdit_taskName")
        self.horizontalLayout_8.addWidget(self.lineEdit_taskName)
        self.label_9 = QtWidgets.QLabel(self.widget_5)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.lineEdit_schedulePeriod = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_schedulePeriod.setText("")
        self.lineEdit_schedulePeriod.setObjectName("lineEdit_schedulePeriod")
        self.horizontalLayout_8.addWidget(self.lineEdit_schedulePeriod)
        self.checkBox_duplicate = QtWidgets.QCheckBox(self.widget_5)
        self.checkBox_duplicate.setObjectName("checkBox_duplicate")
        self.horizontalLayout_8.addWidget(self.checkBox_duplicate)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 80))
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 80))
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.pushButton_exportTask = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_exportTask.setMinimumSize(QtCore.QSize(0, 70))
        self.pushButton_exportTask.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_exportTask.setFont(font)
        self.pushButton_exportTask.setObjectName("pushButton_exportTask")
        self.horizontalLayout_10.addWidget(self.pushButton_exportTask)
        self.verticalLayout_2.addWidget(self.widget_6)
        self.widget_15 = QtWidgets.QWidget(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_15.sizePolicy().hasHeightForWidth())
        self.widget_15.setSizePolicy(sizePolicy)
        self.widget_15.setStyleSheet("")
        self.widget_15.setObjectName("widget_15")
        self.label_3 = QtWidgets.QLabel(self.widget_15)
        self.label_3.setGeometry(QtCore.QRect(70, 30, 72, 15))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.widget_15)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.horizontalLayout_13.addWidget(self.tabWidget_2)
        self.tabWidget.addTab(self.tab_tasklist, "")
        self.horizontalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.widget_right = QtWidgets.QWidget(self.widget)
        self.widget_right.setObjectName("widget_right")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_right)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_16 = QtWidgets.QWidget(self.widget_right)
        self.widget_16.setObjectName("widget_16")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_16)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget1 = QtWidgets.QWidget(self.widget_16)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_10.setSpacing(20)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_19 = QtWidgets.QWidget(self.widget1)
        self.widget_19.setStyleSheet("")
        self.widget_19.setObjectName("widget_19")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_19)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label = QtWidgets.QLabel(self.widget_19)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_14.addWidget(self.label)
        self.pushButton_browserSelectParent = QtWidgets.QPushButton(self.widget_19)
        self.pushButton_browserSelectParent.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_browserSelectParent.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_browserSelectParent.setObjectName("pushButton_browserSelectParent")
        self.horizontalLayout_14.addWidget(self.pushButton_browserSelectParent)
        self.pushButton_browserContent = QtWidgets.QPushButton(self.widget_19)
        self.pushButton_browserContent.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_browserContent.setObjectName("pushButton_browserContent")
        self.horizontalLayout_14.addWidget(self.pushButton_browserContent)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.verticalLayout_10.addWidget(self.widget_19)
        self.plainTextEdit_html = QtWidgets.QPlainTextEdit(self.widget1)
        self.plainTextEdit_html.setObjectName("plainTextEdit_html")
        self.verticalLayout_10.addWidget(self.plainTextEdit_html)
        self.horizontalLayout_2.addWidget(self.widget1)
        self.verticalLayout_8.addWidget(self.widget_16)
        self.widget_17 = QtWidgets.QWidget(self.widget_right)
        self.widget_17.setObjectName("widget_17")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_17)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.widget_18 = QtWidgets.QWidget(self.widget_17)
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_18)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_13.addWidget(self.widget_18)
        self.widget_20 = QtWidgets.QWidget(self.widget_17)
        self.widget_20.setStyleSheet("")
        self.widget_20.setObjectName("widget_20")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.widget_20)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_12 = QtWidgets.QLabel(self.widget_20)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_18.addWidget(self.label_12)
        self.lineEdit_express = QtWidgets.QLineEdit(self.widget_20)
        self.lineEdit_express.setObjectName("lineEdit_express")
        self.horizontalLayout_18.addWidget(self.lineEdit_express)
        self.verticalLayout_13.addWidget(self.widget_20)
        self.widget_7 = QtWidgets.QWidget(self.widget_17)
        self.widget_7.setStyleSheet("")
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_5 = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_17.addWidget(self.label_5)
        self.pushButton_extract_link = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_extract_link.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton_extract_link.setObjectName("pushButton_extract_link")
        self.horizontalLayout_17.addWidget(self.pushButton_extract_link)
        self.pushButton_extract_text = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_extract_text.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton_extract_text.setObjectName("pushButton_extract_text")
        self.horizontalLayout_17.addWidget(self.pushButton_extract_text)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem6)
        self.pushButton_extract_preview = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_extract_preview.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton_extract_preview.setObjectName("pushButton_extract_preview")
        self.horizontalLayout_17.addWidget(self.pushButton_extract_preview)
        self.pushButton_express_save_field = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_express_save_field.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton_express_save_field.setObjectName("pushButton_express_save_field")
        self.horizontalLayout_17.addWidget(self.pushButton_express_save_field)
        self.verticalLayout_13.addWidget(self.widget_7)
        self.plainTextEdit_field_value = QtWidgets.QPlainTextEdit(self.widget_17)
        self.plainTextEdit_field_value.setObjectName("plainTextEdit_field_value")
        self.verticalLayout_13.addWidget(self.plainTextEdit_field_value)
        self.verticalLayout_8.addWidget(self.widget_17)
        self.verticalLayout_8.setStretch(0, 5)
        self.verticalLayout_8.setStretch(1, 5)
        self.horizontalLayout_6.addWidget(self.widget_right)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 7)
        self.horizontalLayout_6.setStretch(2, 3)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1462, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "翻页的xpath表达式："))
        self.label_18.setText(_translate("MainWindow", "翻页次数："))
        self.label_20.setText(_translate("MainWindow", "翻页前停留"))
        self.label_21.setText(_translate("MainWindow", "秒"))
        self.pushButton_pager_test.setText(_translate("MainWindow", "测试翻页"))
        self.checkBox_autopager.setText(_translate("MainWindow", "自动翻页"))
        self.pushButton_load.setText(_translate("MainWindow", "加载页面"))
        self.pushButton_browserSelect.setText(_translate("MainWindow", "开始选择"))
        self.pushButton_browserUnselect.setText(_translate("MainWindow", "取消选择"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_browser), _translate("MainWindow", "浏览器"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_1), _translate("MainWindow", "1、起始网址"))
        self.pushButton_fieldAdd.setText(_translate("MainWindow", "添加"))
        self.pushButton_fieldRemove.setText(_translate("MainWindow", "删除"))
        self.pushButton_fieldCopy.setText(_translate("MainWindow", "复制"))
        self.pushButton_fieldSave.setText(_translate("MainWindow", "保存"))
        self.pushButton_fieldPreview.setText(_translate("MainWindow", "预览"))
        self.pushButton_export.setText(_translate("MainWindow", "导出"))
        self.label_22.setText(_translate("MainWindow", "xpath表达式："))
        self.groupBox.setTitle(_translate("MainWindow", "处理数据"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">定义一个javascript函数，函数名只能是parse，参数就是需要处理的字段值，结构如下</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">function parse(s){</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  //这里写自己的代码</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  return s;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">}</p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "数据展示"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "2、提取字段"))
        self.checkBox_savefile_is.setText(_translate("MainWindow", "保存到文件"))
        self.checkBox_savemysql_is.setText(_translate("MainWindow", "保存到MySQL"))
        self.groupBox_saveFile.setTitle(_translate("MainWindow", "保存到文件"))
        self.pushButton_saveFile_chooseName.setText(_translate("MainWindow", "文件位置"))
        self.label_8.setText(_translate("MainWindow", "分隔符"))
        self.groupBox_savemysql.setTitle(_translate("MainWindow", "保存到MySQL"))
        self.label_13.setText(_translate("MainWindow", "连接地址："))
        self.label_14.setText(_translate("MainWindow", "用户名："))
        self.label_15.setText(_translate("MainWindow", "密码："))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "3、发布信息"))
        self.label_.setText(_translate("MainWindow", "任务名称"))
        self.label_9.setText(_translate("MainWindow", "       调度周期"))
        self.checkBox_duplicate.setText(_translate("MainWindow", " 抓取时去重"))
        self.pushButton_exportTask.setText(_translate("MainWindow", "导出任务"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "4、爬虫设置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tasklist), _translate("MainWindow", "设计器"))
        self.label.setText(_translate("MainWindow", "页面结构>>"))
        self.pushButton_browserSelectParent.setText(_translate("MainWindow", "选择上一级"))
        self.pushButton_browserContent.setText(_translate("MainWindow", "页面内容"))
        self.label_12.setText(_translate("MainWindow", "表达式>>"))
        self.label_5.setText(_translate("MainWindow", "提取操作>>"))
        self.pushButton_extract_link.setText(_translate("MainWindow", "超链接"))
        self.pushButton_extract_text.setText(_translate("MainWindow", "文本"))
        self.pushButton_extract_preview.setText(_translate("MainWindow", "浏览数据"))
        self.pushButton_express_save_field.setText(_translate("MainWindow", "保存字段"))
